### ISSUE TITLE
Googlemaps business info

### ISSUE THREAD

**Issue by stajdini** [gaspa93/googlemaps-scraper#35]
Hi dear Mattia @gaspa93. Would you consider creating a library that pulls data on any business from Googlemaps (business name, avg rating, open hours, price range ($) etc.?

**Comment by gaspa93** [comment]
Hi @stajdini ,

At the moment there is the --place option that allows to obtain the metadata about the place in the url, instead of the reviews. The implementation is very old (it gets only overall rating and number of reviews), but I am already developing the extension to additional information.

Thanks,
Mattia

**Comment by gaspa93** [comment]
Hi @stajdini ,

I merged the latest development. Now the --place parameter produces in output:

- Overall rating
- #reviews
- #photos 
- Category
- Description
- Address 
- Website
- Phone number
- Plus Code
- Opening hours
- Latitude & Longitude

I did not test extensively, so please report any kind of issue you may face. 
Hope it will be useful,
Mattia
