### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by anksng1201** [gaspa93/googlemaps-scraper#8]
Hello,

I am getting an Uncaught RangeError for locations where the reviews are more than 900-1000. This is probably from the `while ` loop in scrapper.py. Is there a way to resolve this. Thanks in advance. 

Best

**Comment by calvinjesselee** [comment]
> Hello,
> 
> I am getting an Uncaught RangeError for locations where the reviews are more than 900-1000. This is probably from the `while ` loop in scrapper.py. Is there a way to resolve this. Thanks in advance.
> 
> Best

Hi, 

Can you please look at the issue I posted and see if you had the same error?

Thanks

**Comment by gaspa93** [comment]
Hi @anksng1201,

I already run some tests about limits and I discovered that at around 1300 reviews, Google Maps website does not load further reviews and it remains blocked while trying to load more: I am not sure if it is a problem of loading more data on the HTML, a memory problem or a limitation that imposed Google itself.

The only thing that it comes to my mind is to add a control that, after a number of scrolls without new data, terminates the program. If you want to scrape more reviews, you have to run the scraper daily or hourly so that you can always stay in the limit of 1300 I think.

Mattia
